# ships_data.py
# AUTO-GENERATED

SHIPS_DB = {
    "100i": {"price": 50, "role": "Starter Luxe", "brand": "Origin", "ingame": True, "auec_price": 700000, "img": "assets/100i.webp"},
    "125a": {"price": 60, "role": "Combat Léger", "brand": "Origin", "ingame": True, "auec_price": 800000, "img": "assets/125a.webp"},
    "135c": {"price": 65, "role": "Fret Léger", "brand": "Origin", "ingame": True, "auec_price": 900000, "img": "assets/135c.webp"},
    "300i": {"price": 60, "role": "Luxe", "brand": "Origin", "ingame": True, "auec_price": 850000, "img": "assets/300i.webp"},
    "315p": {"price": 65, "role": "Exploration", "brand": "Origin", "ingame": True, "auec_price": 950000, "img": "assets/315p.webp"},
    "325a": {"price": 70, "role": "Combat", "brand": "Origin", "ingame": True, "auec_price": 1100000, "img": "assets/325a.webp"},
    "350r": {"price": 125, "role": "Course", "brand": "Origin", "ingame": True, "auec_price": 1600000, "img": "assets/350r.webp"},
    "400i": {"price": 250, "role": "Exploration Luxe", "brand": "Origin", "ingame": True, "auec_price": 5000000, "img": "assets/400i.webp"},
    "600i Explorer": {"price": 475, "role": "Exploration Luxe", "brand": "Origin", "ingame": True, "auec_price": 12500000, "img": "assets/600i explorer.webp"},
    "600i Touring": {"price": 475, "role": "Exploration Luxe", "brand": "Origin", "ingame": True, "auec_price": 12500000, "img": "assets/600i touring.webp"},
    "85x": {"price": 0, "role": "Autre", "brand": "Inconnu", "ingame": False, "auec_price": 0, "img": "assets/85X.webp"},
    "890 Jump": {"price": 950, "role": "Yacht Capital", "brand": "Origin", "ingame": False, "auec_price": 0, "img": "assets/890 jump.webp"},
    "C2 Hercules": {"price": 400, "role": "Fret Lourd", "brand": "Crusader", "ingame": True, "auec_price": 6250000, "img": "assets/C2 hercules.webp"},
    "Carrack W C8X": {"price": 600, "role": "Exploration", "brand": "Anvil", "ingame": True, "auec_price": 26000000, "img": "assets/Carrack w c8x.webp"},
    "A1 Spirit": {"price": 125, "role": "Polyvalent", "brand": "Crusader", "ingame": False, "auec_price": 0, "img": "assets/a1 spirit.webp"},
    "A2 Hercules": {"price": 750, "role": "Bombardier", "brand": "Crusader", "ingame": True, "auec_price": 15000000, "img": "assets/a2 hercules.webp"},
    "Anvil Ballista Dunestalker": {"price": 60, "role": "Chasseur Primes", "brand": "Aegis", "ingame": True, "auec_price": 900000, "img": "assets/anvil ballista dunestalker.webp"},
    "Anvil Ballista Snowblind": {"price": 140, "role": "DCA", "brand": "Anvil", "ingame": True, "auec_price": 1900000, "img": "assets/anvil ballista snowblind.webp"},
    "Apollo Medivac": {"price": 250, "role": "Médical", "brand": "RSI", "ingame": False, "auec_price": 0, "img": "assets/apollo medivac.webp"},
    "Apollo Triage": {"price": 250, "role": "Médical", "brand": "RSI", "ingame": False, "auec_price": 0, "img": "assets/apollo triage.webp"},
    "Ares Inferno": {"price": 250, "role": "Anti-Capital", "brand": "Crusader", "ingame": True, "auec_price": 3800000, "img": "assets/ares inferno.webp"},
    "Ares Ion": {"price": 250, "role": "Anti-Capital", "brand": "Crusader", "ingame": True, "auec_price": 3800000, "img": "assets/ares ion.webp"},
    "Argo Mole Carbon Edition": {"price": 40, "role": "Utilitaire", "brand": "ARGO", "ingame": True, "auec_price": 300000, "img": "assets/argo mole carbon edition.webp"},
    "Argo Mole Talus Edition": {"price": 40, "role": "Utilitaire", "brand": "ARGO", "ingame": True, "auec_price": 300000, "img": "assets/argo mole talus edition.webp"},
    "Arrastra": {"price": 575, "role": "Minage Capital", "brand": "RSI", "ingame": False, "auec_price": 0, "img": "assets/arrastra.webp"},
    "Arrow": {"price": 75, "role": "Chasseur Léger", "brand": "Anvil", "ingame": True, "auec_price": 1050000, "img": "assets/arrow.webp"},
    "Asgard": {"price": 350, "role": "Dropship / Combat", "brand": "Anvil", "ingame": False, "auec_price": 0, "img": "assets/asgard.webp"},
    "Atls Geo": {"price": 40, "role": "Exosquelette", "brand": "ARGO", "ingame": False, "auec_price": 0, "img": "assets/atls geo.webp"},
    "Atls": {"price": 40, "role": "Exosquelette", "brand": "ARGO", "ingame": False, "auec_price": 0, "img": "assets/atls.webp"},
    "Aurora CL": {"price": 30, "role": "Starter", "brand": "RSI", "ingame": True, "auec_price": 300000, "img": "assets/aurora cl.webp"},
    "Aurora ES": {"price": 30, "role": "Starter", "brand": "RSI", "ingame": True, "auec_price": 300000, "img": "assets/aurora es.webp"},
    "Aurora LN": {"price": 30, "role": "Starter", "brand": "RSI", "ingame": True, "auec_price": 300000, "img": "assets/aurora ln.webp"},
    "Aurora LX": {"price": 30, "role": "Starter", "brand": "RSI", "ingame": True, "auec_price": 300000, "img": "assets/aurora lx.webp"},
    "Aurora MR": {"price": 30, "role": "Starter", "brand": "RSI", "ingame": True, "auec_price": 300000, "img": "assets/aurora mr.webp"},
    "Avenger Stalker": {"price": 60, "role": "Chasseur Primes", "brand": "Aegis", "ingame": True, "auec_price": 900000, "img": "assets/avenger stalker.webp"},
    "Avenger Titan Renegade": {"price": 55, "role": "Fret Léger", "brand": "Aegis", "ingame": True, "auec_price": 800000, "img": "assets/avenger titan renegade.webp"},
    "Avenger Titan": {"price": 55, "role": "Fret Léger", "brand": "Aegis", "ingame": True, "auec_price": 800000, "img": "assets/avenger titan.webp"},
    "Avenger Warlock": {"price": 85, "role": "EMP", "brand": "Aegis", "ingame": True, "auec_price": 1800000, "img": "assets/avenger warlock.webp"},
    "Ballista": {"price": 140, "role": "DCA", "brand": "Anvil", "ingame": True, "auec_price": 1900000, "img": "assets/ballista.webp"},
    "Blade": {"price": 275, "role": "Chasseur Léger", "brand": "Vanduul", "ingame": False, "auec_price": 0, "img": "assets/blade.webp"},
    "Buccaneer": {"price": 110, "role": "Intercepteur", "brand": "Drake", "ingame": True, "auec_price": 1450000, "img": "assets/buccaneer.webp"},
    "C1 Spirit": {"price": 125, "role": "Polyvalent", "brand": "Crusader", "ingame": False, "auec_price": 0, "img": "assets/c1 spirit.webp"},
    "C8 Pisces": {"price": 45, "role": "Snub", "brand": "Anvil", "ingame": True, "auec_price": 350000, "img": "assets/c8 pisces.webp"},
    "C8R Pisces": {"price": 45, "role": "Snub", "brand": "Anvil", "ingame": True, "auec_price": 350000, "img": "assets/c8r pisces.webp"},
    "C8X Pisces Expedition": {"price": 45, "role": "Snub", "brand": "Anvil", "ingame": True, "auec_price": 350000, "img": "assets/c8x pisces expedition.webp"},
    "Carrack Expedition W C8X": {"price": 600, "role": "Exploration", "brand": "Anvil", "ingame": True, "auec_price": 26000000, "img": "assets/carrack expedition w C8X.webp"},
    "Carrack Expedition": {"price": 600, "role": "Exploration", "brand": "Anvil", "ingame": True, "auec_price": 26000000, "img": "assets/carrack expedition.webp"},
    "Carrack": {"price": 600, "role": "Exploration", "brand": "Anvil", "ingame": True, "auec_price": 26000000, "img": "assets/carrack.webp"},
    "Carterpillar Best In Show Edition 2949": {"price": 330, "role": "Fret Lourd", "brand": "Drake", "ingame": True, "auec_price": 4650000, "img": "assets/carterpillar best in show edition 2949.webp"},
    "Caterpillar Pirate Edition": {"price": 330, "role": "Fret Lourd", "brand": "Drake", "ingame": True, "auec_price": 4650000, "img": "assets/caterpillar pirate edition.webp"},
    "Caterpillar": {"price": 330, "role": "Fret Lourd", "brand": "Drake", "ingame": True, "auec_price": 4650000, "img": "assets/caterpillar.webp"},
    "Centurion": {"price": 110, "role": "DCA", "brand": "Anvil", "ingame": True, "auec_price": 1400000, "img": "assets/centurion.webp"},
    "Constellation Phoenix Emerald": {"price": 350, "role": "Luxe", "brand": "RSI", "ingame": True, "auec_price": 6500000, "img": "assets/constellation phoenix emerald.webp"},
    "Constellation Phoenix": {"price": 350, "role": "Luxe", "brand": "RSI", "ingame": True, "auec_price": 6500000, "img": "assets/constellation phoenix.webp"},
    "Corsair": {"price": 250, "role": "Exploration", "brand": "Drake", "ingame": True, "auec_price": 5000000, "img": "assets/corsair.webp"},
    "Cosntellation Taurus": {"price": 190, "role": "Fret", "brand": "RSI", "ingame": True, "auec_price": 3200000, "img": "assets/cosntellation taurus.webp"},
    "Crucible": {"price": 350, "role": "Réparation", "brand": "Anvil", "ingame": False, "auec_price": 0, "img": "assets/crucible.webp"},
    "CSV SM": {"price": 0, "role": "Autre", "brand": "Inconnu", "ingame": False, "auec_price": 0, "img": "assets/csv-sm.webp"},
    "Cutlass Black Best In Show Edition 2949": {"price": 110, "role": "Polyvalent", "brand": "Drake", "ingame": True, "auec_price": 1380000, "img": "assets/cutlass black best in show edition 2949.webp"},
    "Cutlass Black": {"price": 110, "role": "Polyvalent", "brand": "Drake", "ingame": True, "auec_price": 1380000, "img": "assets/cutlass black.webp"},
    "Cutlass Blue": {"price": 110, "role": "Polyvalent", "brand": "Drake", "ingame": True, "auec_price": 1380000, "img": "assets/cutlass blue.webp"},
    "Cutlass Red": {"price": 110, "role": "Polyvalent", "brand": "Drake", "ingame": True, "auec_price": 1380000, "img": "assets/cutlass red.webp"},
    "Cutlass Steel": {"price": 110, "role": "Polyvalent", "brand": "Drake", "ingame": True, "auec_price": 1380000, "img": "assets/cutlass steel.webp"},
    "Cutter Rambler": {"price": 45, "role": "Starter", "brand": "Drake", "ingame": True, "auec_price": 500000, "img": "assets/cutter rambler.webp"},
    "Cutter Scout": {"price": 45, "role": "Starter", "brand": "Drake", "ingame": True, "auec_price": 500000, "img": "assets/cutter scout.webp"},
    "Cutter": {"price": 45, "role": "Starter", "brand": "Drake", "ingame": True, "auec_price": 500000, "img": "assets/cutter.webp"},
    "Cyclone AA": {"price": 28, "role": "Véhicule", "brand": "Tumbril", "ingame": True, "auec_price": 190000, "img": "assets/cyclone aa.webp"},
    "Cyclone MT": {"price": 28, "role": "Véhicule", "brand": "Tumbril", "ingame": True, "auec_price": 190000, "img": "assets/cyclone mt.webp"},
    "Cyclone RC": {"price": 28, "role": "Véhicule", "brand": "Tumbril", "ingame": True, "auec_price": 190000, "img": "assets/cyclone rc.webp"},
    "Cyclone RN": {"price": 28, "role": "Véhicule", "brand": "Tumbril", "ingame": True, "auec_price": 190000, "img": "assets/cyclone rn.webp"},
    "Cyclone TR": {"price": 28, "role": "Véhicule", "brand": "Tumbril", "ingame": True, "auec_price": 190000, "img": "assets/cyclone tr.webp"},
    "Cyclone": {"price": 28, "role": "Véhicule", "brand": "Tumbril", "ingame": True, "auec_price": 190000, "img": "assets/cyclone.webp"},
    "Defender": {"price": 220, "role": "Chasseur Alien", "brand": "Banu", "ingame": True, "auec_price": 3600000, "img": "assets/defender.webp"},
    "Dragonfly Black": {"price": 40, "role": "Gravlev", "brand": "Drake", "ingame": True, "auec_price": 150000, "img": "assets/dragonfly black.webp"},
    "Dragonfly Yellowjacket": {"price": 40, "role": "Gravlev", "brand": "Drake", "ingame": True, "auec_price": 150000, "img": "assets/dragonfly yellowjacket.webp"},
    "E1 Spirit": {"price": 125, "role": "Polyvalent", "brand": "Crusader", "ingame": False, "auec_price": 0, "img": "assets/e1 spirit.webp"},
    "Eclipse": {"price": 300, "role": "Bombardier Furtif", "brand": "Aegis", "ingame": True, "auec_price": 6000000, "img": "assets/eclipse.webp"},
    "Endeavor": {"price": 350, "role": "Science", "brand": "MISC", "ingame": False, "auec_price": 0, "img": "assets/endeavor.webp"},
    "Expanse": {"price": 150, "role": "Raffinage", "brand": "MISC", "ingame": False, "auec_price": 0, "img": "assets/expanse.webp"},
    "F7A Hornet Mk I": {"price": 110, "role": "Chasseur Moyen", "brand": "Anvil", "ingame": True, "auec_price": 1500000, "img": "assets/f7a hornet mk i.webp"},
    "F7A Hornet Mk II": {"price": 110, "role": "Chasseur Moyen", "brand": "Anvil", "ingame": True, "auec_price": 1500000, "img": "assets/f7a hornet mk ii.webp"},
    "F7C Honrnet Mk II": {"price": 175, "role": "Chasseur Moyen", "brand": "Anvil", "ingame": False, "auec_price": 0, "img": "assets/f7c honrnet mk II.webp"},
    "F7C Hornet Mk I": {"price": 110, "role": "Chasseur Moyen", "brand": "Anvil", "ingame": True, "auec_price": 1500000, "img": "assets/f7c hornet mk I.webp"},
    "F7C Hornet Wildfire Mk I": {"price": 110, "role": "Chasseur Moyen", "brand": "Anvil", "ingame": True, "auec_price": 1500000, "img": "assets/f7c hornet wildfire mk i.webp"},
    "F7C M Super Hornet Heartseeker Mk I": {"price": 110, "role": "Chasseur Moyen", "brand": "Anvil", "ingame": True, "auec_price": 1500000, "img": "assets/f7c-m super hornet heartseeker mk i.webp"},
    "F7C M Super Hornet Mk I": {"price": 110, "role": "Chasseur Moyen", "brand": "Anvil", "ingame": True, "auec_price": 1500000, "img": "assets/f7c-m super hornet mk i.webp"},
    "F7C M Super Hornet Mk II": {"price": 110, "role": "Chasseur Moyen", "brand": "Anvil", "ingame": True, "auec_price": 1500000, "img": "assets/f7c-m super hornet mk ii.webp"},
    "F7C R Hornet Tracker Mk I": {"price": 110, "role": "Chasseur Moyen", "brand": "Anvil", "ingame": True, "auec_price": 1500000, "img": "assets/f7c-r hornet tracker mk I.webp"},
    "F7C R Hornet Tracker Mk II": {"price": 110, "role": "Chasseur Moyen", "brand": "Anvil", "ingame": True, "auec_price": 1500000, "img": "assets/f7c-r hornet tracker mk II.webp"},
    "F7C S Hornet Ghost Mk I": {"price": 110, "role": "Chasseur Moyen", "brand": "Anvil", "ingame": True, "auec_price": 1500000, "img": "assets/f7c-s hornet ghost mk i.webp"},
    "F7C S Hornet Ghost Mk II": {"price": 110, "role": "Chasseur Moyen", "brand": "Anvil", "ingame": True, "auec_price": 1500000, "img": "assets/f7c-s hornet ghost mk ii.webp"},
    "F8C Lightning Executive Edition": {"price": 300, "role": "Chasseur Lourd", "brand": "Anvil", "ingame": False, "auec_price": 0, "img": "assets/f8c lightning executive edition.webp"},
    "F8C Lightning": {"price": 300, "role": "Chasseur Lourd", "brand": "Anvil", "ingame": False, "auec_price": 0, "img": "assets/f8c lightning.webp"},
    "Fortune": {"price": 175, "role": "Recyclage / Indus", "brand": "MISC", "ingame": False, "auec_price": 0, "img": "assets/fortune.webp"},
    "Freelancer DUR": {"price": 110, "role": "Fret", "brand": "MISC", "ingame": True, "auec_price": 1300000, "img": "assets/freelancer dur.webp"},
    "Freelancer MAX": {"price": 110, "role": "Fret", "brand": "MISC", "ingame": True, "auec_price": 1300000, "img": "assets/freelancer max.webp"},
    "Freelancer MIS": {"price": 110, "role": "Fret", "brand": "MISC", "ingame": True, "auec_price": 1300000, "img": "assets/freelancer mis.webp"},
    "Freelancer": {"price": 110, "role": "Fret", "brand": "MISC", "ingame": True, "auec_price": 1300000, "img": "assets/freelancer.webp"},
    "Fury LX": {"price": 55, "role": "Snub", "brand": "Mirai", "ingame": False, "auec_price": 0, "img": "assets/fury lx.webp"},
    "Fury MX": {"price": 55, "role": "Snub", "brand": "Mirai", "ingame": False, "auec_price": 0, "img": "assets/fury mx.webp"},
    "Fury": {"price": 55, "role": "Snub", "brand": "Mirai", "ingame": False, "auec_price": 0, "img": "assets/fury.webp"},
    "G12": {"price": 0, "role": "Autre", "brand": "Inconnu", "ingame": False, "auec_price": 0, "img": "assets/g12.webp"},
    "G12A": {"price": 0, "role": "Autre", "brand": "Inconnu", "ingame": False, "auec_price": 0, "img": "assets/g12a.webp"},
    "G12r": {"price": 0, "role": "Autre", "brand": "Inconnu", "ingame": False, "auec_price": 0, "img": "assets/g12r.webp"},
    "Galaxy": {"price": 380, "role": "Modulaire", "brand": "RSI", "ingame": False, "auec_price": 0, "img": "assets/galaxy.webp"},
    "Genesis": {"price": 400, "role": "Passagers", "brand": "Crusader", "ingame": False, "auec_price": 0, "img": "assets/genesis.webp"},
    "Gladiator": {"price": 165, "role": "Bombardier", "brand": "Anvil", "ingame": True, "auec_price": 2500000, "img": "assets/gladiator.webp"},
    "Gladius Pirate Edition": {"price": 90, "role": "Chasseur Léger", "brand": "Aegis", "ingame": True, "auec_price": 1250000, "img": "assets/gladius pirate edition.webp"},
    "Gladius Valiant": {"price": 90, "role": "Chasseur Léger", "brand": "Aegis", "ingame": True, "auec_price": 1250000, "img": "assets/gladius valiant.webp"},
    "Gladius": {"price": 90, "role": "Chasseur Léger", "brand": "Aegis", "ingame": True, "auec_price": 1250000, "img": "assets/gladius.webp"},
    "Glaive": {"price": 350, "role": "Chasseur Moyen", "brand": "Vanduul", "ingame": False, "auec_price": 0, "img": "assets/glaive.webp"},
    "Golem": {"price": 60, "role": "Minage", "brand": "Drake", "ingame": False, "auec_price": 0, "img": "assets/golem.webp"},
    "Guardian MX": {"price": 225, "role": "Chasseur Lourd", "brand": "Mirai", "ingame": False, "auec_price": 0, "img": "assets/guardian mx.webp"},
    "Guardian QI": {"price": 225, "role": "Chasseur Lourd", "brand": "Mirai", "ingame": False, "auec_price": 0, "img": "assets/guardian qi.webp"},
    "Guardian": {"price": 225, "role": "Chasseur Lourd", "brand": "Mirai", "ingame": False, "auec_price": 0, "img": "assets/guardian.webp"},
    "Hammerhead Best In Show Edition 2949": {"price": 725, "role": "Corvette", "brand": "Aegis", "ingame": True, "auec_price": 17500000, "img": "assets/hammerhead best in show edition 2949.webp"},
    "Hammerhead": {"price": 725, "role": "Corvette", "brand": "Aegis", "ingame": True, "auec_price": 17500000, "img": "assets/hammerhead.webp"},
    "Hawk": {"price": 100, "role": "Chasseur Primes", "brand": "Anvil", "ingame": True, "auec_price": 1300000, "img": "assets/hawk.webp"},
    "Herarld": {"price": 85, "role": "Données", "brand": "Drake", "ingame": True, "auec_price": 1130000, "img": "assets/herarld.webp"},
    "Hoverquad": {"price": 30, "role": "Gravlev", "brand": "CNOU", "ingame": True, "auec_price": 140000, "img": "assets/hoverquad.webp"},
    "Hull A": {"price": 90, "role": "Fret Léger", "brand": "MISC", "ingame": True, "auec_price": 1150000, "img": "assets/hull a.webp"},
    "Hull B": {"price": 140, "role": "Fret Moyen", "brand": "MISC", "ingame": False, "auec_price": 0, "img": "assets/hull b.webp"},
    "Hull D": {"price": 450, "role": "Fret Lourd", "brand": "MISC", "ingame": False, "auec_price": 0, "img": "assets/hull d.webp"},
    "Hull E": {"price": 750, "role": "Fret Capital", "brand": "MISC", "ingame": False, "auec_price": 0, "img": "assets/hull e.webp"},
    "Hullc": {"price": 350, "role": "Fret Lourd", "brand": "MISC", "ingame": False, "auec_price": 0, "img": "assets/hullc.webp"},
    "Hurricane": {"price": 195, "role": "Chasseur Lourd", "brand": "Anvil", "ingame": True, "auec_price": 3000000, "img": "assets/hurricane.webp"},
    "Idris M": {"price": 1500, "role": "Frégate", "brand": "Aegis", "ingame": False, "auec_price": 0, "img": "assets/idris-m.webp"},
    "Idris P": {"price": 1500, "role": "Frégate", "brand": "Aegis", "ingame": False, "auec_price": 0, "img": "assets/idris-p.webp"},
    "Intrepid": {"price": 65, "role": "Fret Léger", "brand": "Crusader", "ingame": False, "auec_price": 0, "img": "assets/intrepid.webp"},
    "Ironclad Assault": {"price": 450, "role": "Fret Blindé", "brand": "Drake", "ingame": False, "auec_price": 0, "img": "assets/ironclad assault.webp"},
    "Ironclad": {"price": 450, "role": "Fret Blindé", "brand": "Drake", "ingame": False, "auec_price": 0, "img": "assets/ironclad.webp"},
    "Javelin": {"price": 3000, "role": "Destroyer", "brand": "Aegis", "ingame": False, "auec_price": 0, "img": "assets/javelin.webp"},
    "Khartu Ai": {"price": 170, "role": "Eclaireur", "brand": "Aopoa", "ingame": True, "auec_price": 2800000, "img": "assets/khartu-AI.webp"},
    "Kraken Privateer": {"price": 1650, "role": "Porte-Vaisseaux", "brand": "Drake", "ingame": False, "auec_price": 0, "img": "assets/kraken privateer.webp"},
    "Kraken": {"price": 1650, "role": "Porte-Vaisseaux", "brand": "Drake", "ingame": False, "auec_price": 0, "img": "assets/kraken.webp"},
    "L 21 Wolf": {"price": 0, "role": "Autre", "brand": "Inconnu", "ingame": False, "auec_price": 0, "img": "assets/l-21 wolf.webp"},
    "Legionnaire": {"price": 120, "role": "Abordage", "brand": "Anvil", "ingame": False, "auec_price": 0, "img": "assets/legionnaire.webp"},
    "Liberator": {"price": 575, "role": "Transport", "brand": "Anvil", "ingame": False, "auec_price": 0, "img": "assets/liberator.webp"},
    "Lynx": {"price": 60, "role": "Rover Luxe", "brand": "RSI", "ingame": False, "auec_price": 0, "img": "assets/lynx.webp"},
    "M2 Hercules": {"price": 520, "role": "Transport Militaire", "brand": "Crusader", "ingame": True, "auec_price": 10500000, "img": "assets/m2 hercules.webp"},
    "M50": {"price": 0, "role": "Autre", "brand": "Inconnu", "ingame": False, "auec_price": 0, "img": "assets/m50.webp"},
    "Mantis": {"price": 150, "role": "Interdiction", "brand": "RSI", "ingame": True, "auec_price": 2250000, "img": "assets/mantis.webp"},
    "Merchantman": {"price": 650, "role": "Commerce Alien", "brand": "Banu", "ingame": False, "auec_price": 0, "img": "assets/merchantman.webp"},
    "Mercury": {"price": 260, "role": "Données", "brand": "Crusader", "ingame": True, "auec_price": 4500000, "img": "assets/mercury.webp"},
    "Meteor": {"price": 260, "role": "Chasseur Moyen", "brand": "RSI", "ingame": False, "auec_price": 0, "img": "assets/meteor.webp"},
    "Mole": {"price": 315, "role": "Minage", "brand": "ARGO", "ingame": True, "auec_price": 5000000, "img": "assets/mole.webp"},
    "MPUV Cargo": {"price": 40, "role": "Utilitaire", "brand": "ARGO", "ingame": True, "auec_price": 300000, "img": "assets/mpuv cargo.webp"},
    "MPUV Personnel": {"price": 40, "role": "Transport", "brand": "ARGO", "ingame": True, "auec_price": 50000, "img": "assets/mpuv personnel.webp"},
    "MPUV Tractor": {"price": 40, "role": "Manutention", "brand": "ARGO", "ingame": True, "auec_price": 55000, "img": "assets/mpuv tractor.webp"},
    "Mtc": {"price": 50, "role": "Combat Sol", "brand": "Greycat", "ingame": True, "auec_price": 45000, "img": "assets/mtc.webp"},
    "Mule": {"price": 45, "role": "Fret Sol", "brand": "Drake", "ingame": True, "auec_price": 35000, "img": "assets/mule.webp"},
    "Mustang Alpha Vindicator": {"price": 30, "role": "Starter", "brand": "CNOU", "ingame": True, "auec_price": 350000, "img": "assets/mustang alpha vindicator.webp"},
    "Mustang Alpha": {"price": 30, "role": "Starter", "brand": "CNOU", "ingame": True, "auec_price": 350000, "img": "assets/mustang alpha.webp"},
    "Mustang Beta": {"price": 30, "role": "Starter", "brand": "CNOU", "ingame": True, "auec_price": 350000, "img": "assets/mustang beta.webp"},
    "Mustang Delta": {"price": 30, "role": "Starter", "brand": "CNOU", "ingame": True, "auec_price": 350000, "img": "assets/mustang delta.webp"},
    "Mustang Gamma": {"price": 30, "role": "Starter", "brand": "CNOU", "ingame": True, "auec_price": 350000, "img": "assets/mustang gamma.webp"},
    "Mustang Omega": {"price": 30, "role": "Starter", "brand": "CNOU", "ingame": True, "auec_price": 350000, "img": "assets/mustang omega.webp"},
    "Nautilius": {"price": 725, "role": "Mineur", "brand": "Aegis", "ingame": False, "auec_price": 0, "img": "assets/nautilius.webp"},
    "Nautilus Solstice Edition": {"price": 725, "role": "Mineur", "brand": "Aegis", "ingame": False, "auec_price": 0, "img": "assets/nautilus solstice edition.webp"},
    "Nomad": {"price": 80, "role": "Starter Avancé", "brand": "CNOU", "ingame": True, "auec_price": 1050000, "img": "assets/nomad.webp"},
    "Nova": {"price": 120, "role": "Char", "brand": "Tumbril", "ingame": True, "auec_price": 2200000, "img": "assets/nova.webp"},
    "Nox Kue": {"price": 0, "role": "Autre", "brand": "Inconnu", "ingame": False, "auec_price": 0, "img": "assets/nox kue.webp"},
    "Nox": {"price": 0, "role": "Autre", "brand": "Inconnu", "ingame": False, "auec_price": 0, "img": "assets/nox.webp"},
    "Odyssey": {"price": 700, "role": "Exploration", "brand": "MISC", "ingame": False, "auec_price": 0, "img": "assets/odyssey.webp"},
    "Orion": {"price": 650, "role": "Minage Capital", "brand": "RSI", "ingame": False, "auec_price": 0, "img": "assets/orion.webp"},
    "P 52 Merlin": {"price": 0, "role": "Autre", "brand": "Inconnu", "ingame": False, "auec_price": 0, "img": "assets/p-52 merlin.webp"},
    "P 72 Archimedes Emerlad": {"price": 0, "role": "Autre", "brand": "Inconnu", "ingame": False, "auec_price": 0, "img": "assets/p-72 archimedes emerlad.webp"},
    "P 72 Archimedes": {"price": 0, "role": "Autre", "brand": "Inconnu", "ingame": False, "auec_price": 0, "img": "assets/p-72 archimedes.webp"},
    "Paladin": {"price": 350, "role": "Gunship", "brand": "Anvil", "ingame": False, "auec_price": 0, "img": "assets/paladin.webp"},
    "Perseus": {"price": 675, "role": "Gunship Lourd", "brand": "RSI", "ingame": False, "auec_price": 0, "img": "assets/perseus.webp"},
    "Pioneer": {"price": 850, "role": "Construction", "brand": "CNOU", "ingame": False, "auec_price": 0, "img": "assets/pioneer.webp"},
    "Polaris": {"price": 750, "role": "Corvette", "brand": "RSI", "ingame": False, "auec_price": 0, "img": "assets/polaris.webp"},
    "Prospector": {"price": 155, "role": "Minage", "brand": "MISC", "ingame": True, "auec_price": 2000000, "img": "assets/prospector.webp"},
    "Prowler Utility": {"price": 440, "role": "Dropship", "brand": "Tevarin", "ingame": True, "auec_price": 9500000, "img": "assets/prowler utility.webp"},
    "Prowler": {"price": 440, "role": "Dropship", "brand": "Tevarin", "ingame": True, "auec_price": 9500000, "img": "assets/prowler.webp"},
    "PTV": {"price": 15, "role": "Buggy", "brand": "Greycat", "ingame": True, "auec_price": 15000, "img": "assets/ptv.webp"},
    "Pulse Kx": {"price": 30, "role": "Gravlev", "brand": "Mirai", "ingame": False, "auec_price": 0, "img": "assets/pulse kx.webp"},
    "Pulse": {"price": 30, "role": "Gravlev", "brand": "Mirai", "ingame": False, "auec_price": 0, "img": "assets/pulse.webp"},
    "Raft": {"price": 125, "role": "Fret", "brand": "ARGO", "ingame": True, "auec_price": 1700000, "img": "assets/raft.webp"},
    "Railen": {"price": 225, "role": "Fret Alien", "brand": "Gatac", "ingame": False, "auec_price": 0, "img": "assets/railen.webp"},
    "Ranger Cv": {"price": 35, "role": "Moto", "brand": "Tumbril", "ingame": False, "auec_price": 0, "img": "assets/ranger cv.webp"},
    "Ranger RC": {"price": 35, "role": "Moto", "brand": "Tumbril", "ingame": False, "auec_price": 0, "img": "assets/ranger rc.webp"},
    "Ranger TR": {"price": 35, "role": "Moto", "brand": "Tumbril", "ingame": False, "auec_price": 0, "img": "assets/ranger tr.webp"},
    "Razor EX": {"price": 145, "role": "Course", "brand": "MISC", "ingame": True, "auec_price": 1900000, "img": "assets/razor ex.webp"},
    "Razor LX": {"price": 145, "role": "Course", "brand": "MISC", "ingame": True, "auec_price": 1900000, "img": "assets/razor lx.webp"},
    "Razor": {"price": 145, "role": "Course", "brand": "MISC", "ingame": True, "auec_price": 1900000, "img": "assets/razor.webp"},
    "Reclaimer Best In Show Edition 2949": {"price": 400, "role": "Recyclage Lourd", "brand": "Aegis", "ingame": True, "auec_price": 12500000, "img": "assets/reclaimer best in show edition 2949.webp"},
    "Reclaimer": {"price": 400, "role": "Recyclage Lourd", "brand": "Aegis", "ingame": True, "auec_price": 12500000, "img": "assets/reclaimer.webp"},
    "Reliant Kore": {"price": 65, "role": "Starter", "brand": "MISC", "ingame": True, "auec_price": 900000, "img": "assets/reliant kore.webp"},
    "ROC DS": {"price": 55, "role": "Minage Sol", "brand": "Greycat", "ingame": True, "auec_price": 270000, "img": "assets/roc-ds.webp"},
    "ROC": {"price": 55, "role": "Minage Sol", "brand": "Greycat", "ingame": True, "auec_price": 270000, "img": "assets/roc.webp"},
    "Salvation": {"price": 60, "role": "Sauvetage Léger", "brand": "RSI", "ingame": False, "auec_price": 0, "img": "assets/salvation.webp"},
    "San'tok.yai": {"price": 220, "role": "Chasseur Alien", "brand": "Aopoa", "ingame": False, "auec_price": 0, "img": "assets/san'tok.yai.webp"},
    "Scorpius Antares": {"price": 230, "role": "Guerre Elec.", "brand": "RSI", "ingame": False, "auec_price": 0, "img": "assets/scorpius antares.webp"},
    "Scorpius": {"price": 240, "role": "Chasseur Lourd", "brand": "RSI", "ingame": True, "auec_price": 3500000, "img": "assets/scorpius.webp"},
    "Scrythe": {"price": 300, "role": "Chasseur Moyen", "brand": "Vanduul", "ingame": False, "auec_price": 0, "img": "assets/scrythe.webp"},
    "Shiv": {"price": 150, "role": "Chasseur Lourd", "brand": "Vanduul", "ingame": False, "auec_price": 0, "img": "assets/shiv.webp"},
    "Spartan": {"price": 80, "role": "Transport", "brand": "Anvil", "ingame": True, "auec_price": 1000000, "img": "assets/spartan.webp"},
    "SRV": {"price": 150, "role": "Remorquage", "brand": "ARGO", "ingame": False, "auec_price": 0, "img": "assets/srv.webp"},
    "Starfarer Femini": {"price": 300, "role": "Ravitaillement", "brand": "MISC", "ingame": True, "auec_price": 8000000, "img": "assets/starfarer femini.webp"},
    "Starfarer": {"price": 300, "role": "Ravitaillement", "brand": "MISC", "ingame": True, "auec_price": 8000000, "img": "assets/starfarer.webp"},
    "Starlancer MAX": {"price": 240, "role": "Fret", "brand": "MISC", "ingame": False, "auec_price": 0, "img": "assets/starlancer max.webp"},
    "Starlancer Tac": {"price": 275, "role": "Combat", "brand": "MISC", "ingame": False, "auec_price": 0, "img": "assets/starlancer tac.webp"},
    "Storm AA": {"price": 100, "role": "Char Léger", "brand": "Tumbril", "ingame": False, "auec_price": 0, "img": "assets/storm aa.webp"},
    "Storm": {"price": 100, "role": "Char Léger", "brand": "Tumbril", "ingame": False, "auec_price": 0, "img": "assets/storm.webp"},
    "Stringer": {"price": 315, "role": "Chasseur Lourd", "brand": "Vanduul", "ingame": False, "auec_price": 0, "img": "assets/stringer.webp"},
    "STV": {"price": 40, "role": "Véhicule", "brand": "Greycat", "ingame": True, "auec_price": 210000, "img": "assets/stv.webp"},
    "Syulen": {"price": 70, "role": "Starter Alien", "brand": "Gatac", "ingame": False, "auec_price": 0, "img": "assets/syulen.webp"},
    "Talon": {"price": 115, "role": "Chasseur Alien", "brand": "Tevarin", "ingame": True, "auec_price": 1750000, "img": "assets/talon .webp"},
    "Talon Shrike": {"price": 115, "role": "Chasseur Alien", "brand": "Tevarin", "ingame": True, "auec_price": 1750000, "img": "assets/talon shrike.webp"},
    "Terrapin Medic": {"price": 220, "role": "Exploration", "brand": "Anvil", "ingame": True, "auec_price": 4200000, "img": "assets/terrapin medic.webp"},
    "Terrapin": {"price": 220, "role": "Exploration", "brand": "Anvil", "ingame": True, "auec_price": 4200000, "img": "assets/terrapin.webp"},
    "Ursa Fortuna": {"price": 50, "role": "Rover", "brand": "RSI", "ingame": True, "auec_price": 280000, "img": "assets/ursa fortuna.webp"},
    "Ursa Medivac": {"price": 50, "role": "Rover", "brand": "RSI", "ingame": True, "auec_price": 280000, "img": "assets/ursa medivac.webp"},
    "Ursa": {"price": 50, "role": "Rover", "brand": "RSI", "ingame": True, "auec_price": 280000, "img": "assets/ursa.webp"},
    "Valkyrie Liberator Edition": {"price": 575, "role": "Transport", "brand": "Anvil", "ingame": False, "auec_price": 0, "img": "assets/valkyrie liberator edition.webp"},
    "Valkyrie": {"price": 375, "role": "Dropship", "brand": "Anvil", "ingame": True, "auec_price": 6000000, "img": "assets/valkyrie.webp"},
    "Vanguard Harbinger": {"price": 260, "role": "Chasseur Lourd", "brand": "Aegis", "ingame": True, "auec_price": 4500000, "img": "assets/vanguard harbinger.webp"},
    "Vanguard Hoplite": {"price": 260, "role": "Chasseur Lourd", "brand": "Aegis", "ingame": True, "auec_price": 4500000, "img": "assets/vanguard hoplite.webp"},
    "Vanguard Sentinel": {"price": 260, "role": "Chasseur Lourd", "brand": "Aegis", "ingame": True, "auec_price": 4500000, "img": "assets/vanguard sentinel.webp"},
    "Vanguard Warden": {"price": 260, "role": "Chasseur Lourd", "brand": "Aegis", "ingame": True, "auec_price": 4500000, "img": "assets/vanguard warden.webp"},
    "Vulcan": {"price": 200, "role": "Réparation", "brand": "Aegis", "ingame": False, "auec_price": 0, "img": "assets/vulcan.webp"},
    "Vulture": {"price": 175, "role": "Recyclage", "brand": "Drake", "ingame": True, "auec_price": 2800000, "img": "assets/vulture.webp"},
    "X1 Force": {"price": 0, "role": "Autre", "brand": "Inconnu", "ingame": False, "auec_price": 0, "img": "assets/x1 force.webp"},
    "X1 Velocity": {"price": 0, "role": "Autre", "brand": "Inconnu", "ingame": False, "auec_price": 0, "img": "assets/x1 velocity.webp"},
    "X1": {"price": 0, "role": "Autre", "brand": "Inconnu", "ingame": False, "auec_price": 0, "img": "assets/x1.webp"},
    "Zeus Mk II CL": {"price": 150, "role": "Polyvalent", "brand": "RSI", "ingame": False, "auec_price": 0, "img": "assets/zeus mk II cl.webp"},
    "Zeus Mk II ES": {"price": 150, "role": "Polyvalent", "brand": "RSI", "ingame": False, "auec_price": 0, "img": "assets/zeus mk II es.webp"},
    "Zeus Mk II MR": {"price": 150, "role": "Polyvalent", "brand": "RSI", "ingame": False, "auec_price": 0, "img": "assets/zeus mk ii mr.webp"},
}
